# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Next Starter CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  NEXT_PUBLIC_VERSION: 'Version: 0.0.1'

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.0.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: 'Install dependencies'
        run: npm ci
      - name: 'Building project'
        run: npm run build --if-present
      - name: 'Runing lint'
        run: npm run lint
      - name: 'Check code format'
        run: npm run format
      - name: 'Running unitary tests'
        run: npm run test:unit
      - name: 'Install Playwright Browsers'
        run: npx playwright install --with-deps
      - name: 'Run Playwright(e2e) tests'
        run: npm run test:e2e
